# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-04 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_userprofile_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='choice',
        ),
    ]
