# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-07 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_auto_20180807_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
