# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-07 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_auto_20180807_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allot',
            name='user',
        ),
    ]
